CREATE TABLE `businessSubmissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessDescription` text,
	`sportCategoryId` int NOT NULL,
	`businessTypeId` int NOT NULL,
	`city` varchar(100),
	`state` varchar(100),
	`country` varchar(100),
	`region` varchar(100),
	`hub` varchar(100),
	`contactName` varchar(255) NOT NULL,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(30),
	`website` varchar(500),
	`instagram` varchar(255),
	`facebook` varchar(255),
	`additionalNotes` text,
	`submittedByUserId` int,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewNotes` text,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `businessSubmissions_id` PRIMARY KEY(`id`)
);
